name = "quattestor/cardano"
version = "0.0.0"
compiler = "v1.1.24"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'quattestor/cardano'"

[repository]
user = "quattestor"
project = "cardano"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v4.0.0"
source = "github"

[config]
